# Generated by Django 3.1.3 on 2021-01-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolid', models.AutoField(primary_key=True, serialize=False)),
                ('schoolname', models.CharField(max_length=50, null=True)),
                ('school_img', models.ImageField(blank=True, default='download.png', null=True, upload_to='')),
                ('schoolcontactno', models.CharField(max_length=13, null=True)),
                ('schooladdress', models.CharField(max_length=500)),
                ('createddate', models.DateTimeField(null=True)),
                ('schoolemail', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
