# Generated by Django 3.1.3 on 2021-01-23 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignmentid', models.AutoField(primary_key=True, serialize=False)),
                ('assignmentname', models.CharField(max_length=50)),
                ('assignment', models.FileField(default='no assignment yet', upload_to='images')),
                ('duedate', models.DateTimeField()),
                ('createddate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursedescription', models.CharField(max_length=500, null=True)),
                ('coursename', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='schoolTeacher',
            fields=[
                ('teacherid', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('t_img', models.ImageField(blank=True, default='download.png', null=True, upload_to='')),
                ('regno', models.CharField(max_length=20)),
                ('joiningdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionid', models.AutoField(primary_key=True, serialize=False)),
                ('sectionname', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('regno', models.CharField(max_length=20, null=True)),
                ('registrationdate', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('std_profile', models.ImageField(blank=True, default='download.png', null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitAssignment',
            fields=[
                ('uploadid', models.AutoField(primary_key=True, serialize=False)),
                ('uploadurl', models.FileField(default='Not Uploaded yet', max_length=500, null=True, upload_to='images')),
                ('createddate', models.DateTimeField(auto_now_add=True, null=True)),
                ('assignmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.assignment')),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finalapp.course')),
                ('studentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finalapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='TblClass',
            fields=[
                ('classid', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50, null=True)),
                ('class_code', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(null=True)),
                ('endtime', models.DateTimeField(null=True)),
                ('allocationstatus', models.CharField(max_length=100, null=True)),
                ('classid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.tblclass')),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.course')),
                ('dayid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.day')),
                ('sectionid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.section')),
            ],
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.AddField(
            model_name='section',
            name='classid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finalapp.tblclass'),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.tblclass'),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='courseid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalapp.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='classid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.tblclass'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.tblclass'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='courseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacherid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='finalapp.schoolteacher'),
        ),
    ]
