# Generated by Django 3.1.3 on 2021-01-24 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_auto_20210123_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finalapp.tblclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='sectionid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finalapp.section'),
        ),
    ]
