# Generated by Django 3.1.3 on 2021-01-24 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalapp', '0003_auto_20210124_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='allocationstatus',
        ),
        migrations.AddField(
            model_name='tblclass',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
