# Generated by Django 3.1.3 on 2021-01-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_auto_20210124_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblclass',
            name='user',
        ),
        migrations.AddField(
            model_name='timetable',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
