# Generated by Django 3.1.3 on 2021-01-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0006_auto_20210124_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
