# Generated by Django 3.1.3 on 2021-01-24 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0007_delete_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tt_name', models.CharField(max_length=200, null=True)),
                ('starttime', models.DateTimeField(null=True)),
                ('endtime', models.DateTimeField(null=True)),
                ('classid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.tblclass')),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.course')),
                ('dayid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.day')),
                ('sectionid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.section')),
            ],
        ),
    ]
