# Generated by Django 3.1.3 on 2021-01-24 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0008_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('studentresultid', models.AutoField(primary_key=True, serialize=False)),
                ('totalmarks', models.IntegerField(null=True)),
                ('marksobtained', models.IntegerField(null=True)),
                ('classid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.tblclass')),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.course')),
                ('sectionid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.section')),
                ('studentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.student')),
            ],
        ),
    ]
