# Generated by Django 3.1.3 on 2021-01-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0009_studentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('studentattid', models.AutoField(primary_key=True, serialize=False)),
                ('totalclasses', models.IntegerField(null=True)),
                ('classesattended', models.IntegerField(null=True)),
                ('classid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.tblclass')),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.course')),
                ('studentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.student')),
            ],
        ),
    ]
