# Generated by Django 3.1.3 on 2021-01-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0011_auto_20210124_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment',
            field=models.FileField(default='no assignment yet', max_length=500, upload_to='images'),
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('testid', models.AutoField(primary_key=True, serialize=False)),
                ('uploadurl', models.FileField(default='Not Uploaded yet', max_length=500, null=True, upload_to='images')),
                ('classid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.tblclass')),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.course')),
                ('dayid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.day')),
                ('teacherid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.schoolteacher')),
            ],
        ),
    ]
