# Generated by Django 3.1.3 on 2021-01-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0012_auto_20210124_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('formid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('message', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
