# Generated by Django 3.1.3 on 2021-01-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0013_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StudentComplaint',
            fields=[
                ('complaintid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], default='none', max_length=100)),
                ('submitdate', models.DateField(null=True)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.course')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.student')),
                ('teacherid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.schoolteacher')),
            ],
        ),
    ]
