# Generated by Django 3.1.3 on 2021-01-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0014_auto_20210125_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcomplaint',
            name='courseid',
        ),
        migrations.RemoveField(
            model_name='studentcomplaint',
            name='studentid',
        ),
        migrations.RemoveField(
            model_name='studentcomplaint',
            name='teacherid',
        ),
        migrations.AddField(
            model_name='studentcomplaint',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcomplaint',
            name='s_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcomplaint',
            name='teachername',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
