# Generated by Django 3.1.3 on 2021-01-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0017_auto_20210125_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='testname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentcomplaint',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
