# Generated by Django 3.1.3 on 2021-01-27 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0018_auto_20210127_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='std_test',
            fields=[
                ('std_testid', models.AutoField(primary_key=True, serialize=False)),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.course')),
                ('teacherid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalapp.schoolteacher')),
            ],
        ),
    ]
